package com.example.promptsharepro22.data.model;

import java.util.HashMap;
import java.util.Map;

// User.java
public class User {
    private String id;
    private String username;
    private String password;
    private String email;
    private String USCID;
    private String firstName;
    private String lastName;
    private String createdAt;

    // Empty constructor for Firebase
    public User() {}

    // Constructor with parameters
    public User(String username, String password, String email, String USCID, String createdAt) {
        this.id = null; // ID will be auto-generated by Firebase
        this.username = username;
        this.password = password;
        this.email = email;
        this.USCID = USCID;
        this.firstName = "Tommy";
        this.lastName = "Trojan";
        this.createdAt = createdAt;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    public String getEmail() {
        return email;
    }

    public String getUSCID() {
        return USCID;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setUSCID(String USCID) {
        this.USCID = USCID;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    // Method to create a Map for partial updates
    public Map<String, Object> buildUpdateMap() {
        Map<String, Object> updateMap = new HashMap<>();
        if (username != null) updateMap.put("username", username);
        if (password != null) updateMap.put("password", password);
        if (email != null) updateMap.put("email", email);
        if (USCID != null) updateMap.put("USCID", USCID);
        if (firstName != null) updateMap.put("firstName", firstName);
        if (lastName != null) updateMap.put("lastName", lastName);
        if (createdAt != null) updateMap.put("createdAt", createdAt);
        return updateMap;
    }

}
